# Data Manipulation with Pandas

<div class="alert alert-block alert-danger">
<b>Check the Kernel you are using:</b> Before we get started, if you are running this on HiPerGator, double check the kernel in use. This is shown in the top right of the window and should look like: <img src="images/kernel.python310.png" alt"Image showing that the notebook is using the Python 3.10 kernel" style="float:right">
</div>

This notebook is based on [chapter 3 of Jake VanderPlas' Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/03.00-introduction-to-pandas.html). [<img src="images/PDSH-cover-small.png" alt="PDSH Cover Image" style="width: 50px;float:right"/>](https://jakevdp.github.io/PythonDataScienceHandbook/03.00-introduction-to-pandas.html)

As the chapter points out, Pandas builds on NumPy. We saw how NumPy has great features for fast, memory efficient numerical computations. But if you think about data, it is often organized in tables. NumPy has no functionality to label columns or rows with meaningful names. Reffering to managing data, which often include missing values and non-conforming data types, the text notes:
> Pandas, and in particular its `Series` and `DataFrame` objects, builds on the NumPy array structure and provides efficient access to these sorts of "data munging" tasks that occupy much of a data scientist's time.

Let's load NumPy and Pandas, using the standard alias `pd` and get the version we have:

In [1]:
import numpy as np
import pandas as pd
pd.__version__

# Pandas DataFrames in Python are multidimensional arrays with attached row and column labels, and often with heterogeneous types of data. They are like enhanced NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices.

'2.2.3'

The text mentions the three main data types that Pandas provides: `Series`, `DataFrame` and `Index`. We'll stat with `Series` as it helps connect NumPy arrays with Pandas objects.

## Pandas `Series`

In [2]:
# A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows:
data = pd.Series([1,2,3])
print(data)

data2 = pd.Series([1.1,3.0,3.9])
print(data2)

0    1
1    2
2    3
dtype: int64
0    1.1
1    3.0
2    3.9
dtype: float64

> As we see in the output, the `Series` wraps both a sequence of values and a sequence of indices, which we can access with the `values` and `index` attributes. The `values` are simply a familiar NumPy array:

In [3]:
data.values

array([1, 2, 3])

> The `Index` is an array-like object of type `pd.Index`:

In [4]:
data.index

RangeIndex(start=0, stop=3, step=1)

> The essential difference \[between a NymPy array and a Pandas `Series`\] is the presence of the index: while the Numpy Array has an *implicitly* defined integer index used to access the values, the Pandas `Series` has an *explicitly* defined index associated with the values.

In [4]:
# Indices do not need to be integers:

data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
print("data:", "\n", data, "\n")

# Thus, in a Pandas Series, data can be accessed by the associated index name:
print("data['a']:", data['a'])


# General format for constructing Series objects:
### pd.Series(data, index=index)

data:
 a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

data['a']: 0.25

As the text points out, this is similar to a Python dictionary. But with Pandas `Series` both the index and the values are typed. As with NymPy arrays, the explicit typing in `Series` adds efficiency in memory and computation.

## Pandas `DataFrame`

The main data structure that makes Pandas popular is the `DataFrame` class. 

> If a `Series` is an analog of a one-dimensional array with flexible indices, a `DataFrame` is an analog of a two-dimensional array with both flexible row indices and flexible column names.

Here's the example of two `Series` that the text uses to combine into a `DataFrame`:

In [5]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [6]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [7]:
state = pd.DataFrame({'population': population, 'area' : area})
state

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [9]:
# The 'row names' in the DataFrame are called 'indices', or collectively the 'index' 
# In addition to the row index, DataFrames have column names stored in their own index object:
print(state.index) # this attribute reports the indices or row labels of the data frame
print(state.columns) # this attribute reports the column names or column indices of the data frame

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['population', 'area'], dtype='object')

## Accessing data in `DataFrame`s

In [10]:
# You can access a particular column by name in square brackets:
print("state['area']:", "\n", state['area'], "\n") 

# Confusing but important note: 
    ## In a 2D NumPy array, data[0] will return the first ROW.
    ## However, in a 2D Pandas DataFrame, data['name0'] will return the first COLUMN.

state['area']:
 California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [11]:
# You can also access a particular column by name by calling a .attribute of the object:
state.area # Careful, though: Using attributes can break

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [12]:
state['density'] = state['population'] / state['area'] # Add a new column
print(state)

            population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

#### Creating DataFrames:

In [13]:
# We saw above that you can create a DataFrame by combining multiple Series objects:
state = pd.DataFrame({'population': population, 'area' : area, 'density' : state['population'] / state['area']})
print(state, "\n")

# You can also create a DataFrame from a single Series by assigning it a column name:
print(type(population), "\n")
popDF = pd.DataFrame(population, columns=['population'])
print(popDF)
print(type(popDF), "\n")

# In addition, you can create a DataFrame from a 2D NumPy array using any specified column and index (row) names:
Example_Numpy_Array = np.random.rand(3,2)
print(type(Example_Numpy_Array), "\n")
Example_Pandas_DF = pd.DataFrame(Example_Numpy_Array, columns=['foo', 'bar'], index=['a', 'b', 'c'])
print(type(Example_Pandas_DF), "\n")
print(Example_Pandas_DF, "\n")

# Moreover, you can create a DataFrame from a NumPy structured array directly without specifying labels:
A = np.zeros(3, dtype=[('A', 'i8'),('B','f8')])
print(type(A), "\n")
print(pd.DataFrame(A), "\n")
print(type(pd.DataFrame(A)))

            population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

<class 'pandas.core.series.Series'>

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
<class 'pandas.core.frame.DataFrame'>

<class 'numpy.ndarray'>

<class 'pandas.core.frame.DataFrame'>

        foo       bar
a  0.746425  0.114801
b  0.958195  0.424447
c  0.822154  0.084989

<class 'numpy.ndarray'>

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

<class 'pandas.core.frame.DataFrame'>

In [31]:
# Note that, unlike arrays, Index objects are immutable. They cannot be modified via the normal means:
# Example_Pandas_DF.index[1] = 0 # Running this line of code will generate the error message "Index does not support mutable operations"

## Indexing series

In [14]:
# Indexing series:
example_series = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
print(example_series, "\n") # example series

## Indexing via slicing by explicit index:
print([example_series['a':'c']], "\n")

## Indexing via slicing by implicit integer index:
print([example_series[0:2]], "\n") 
### Confusing but important note: 
    #### When slicing with an explicit index (ie, data['a':'c']), the final index is INCLUDED in the slice.
    #### However, when slicing with an implicit index (ie, data[0:2]), the final index is EXCLUDED from the slice.

## Indexing via masking:
print(data[(data > 0.3) & (data < 0.8)], "\n") 

## Indexing via fancy indexing:
print(data[['a', 'd']], "\n") 

# See text for loc and iloc attributes that are used to reference explicit vs. implicit indices blatantly as needed.

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

[a    0.25
b    0.50
c    0.75
dtype: float64]

[a    0.25
b    0.50
dtype: float64]

b    0.50
c    0.75
dtype: float64

a    0.25
d    1.00
dtype: float64

## Indexing & Manipulating DataFrames

In [16]:
print(state, "\n")
print(state.values, "\n")

# Transpose data with data.T:
print(state.T)

# Passing a single index to an array accesses a row:
state.values[0]

# However, passing a single index to a DataFrame accesses a column:
state['area']

            population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

[[3.83325210e+07 4.23967000e+05 9.04139261e+01]
 [2.64481930e+07 6.95662000e+05 3.80187404e+01]
 [1.96511270e+07 1.41297000e+05 1.39076746e+02]
 [1.95528600e+07 1.70312000e+05 1.14806121e+02]
 [1.28821350e+07 1.49995000e+05 8.58837628e+01]]

              California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02

                Illinois
population  1.288214e+07
area        1.499950e+05
density     8.588376e+01

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

> Thus for array-style indexing, we need another convention. Here Pandas again uses the loc, iloc, and ix indexers mentioned earlier. Using the iloc indexer, we can index the underlying array as if it is a simple NumPy array (using the implicit Python-style index), but the DataFrame index and column labels are maintained in the result:

In [18]:
# iloc interprets the resulting numeric inputs as implicit integer indices:
state.iloc[:3, :2]

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

>Similarly, using the loc indexer, we can index the underlying data in an array-like style but using the explicit index and column names:

In [19]:
print(state.loc[:'Illinois', :'population'], "\n")

print(state.loc['Illinois', :'population'], "\n")

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

population    12882135.0
Name: Illinois, dtype: float64

Note: The "ix" indexer used to allow for a hybrid of these two approaches (e.g., "state.ix[3, :'population']"), but now it is deprecated and you can only use one or the other.

>Any of the familiar NumPy-style data access patterns can be used within these indexers. For example, in the loc indexer we can combine masking and fancy indexing as in the following:

In [20]:
state.loc[state.density > 100, ['population', 'density']] 
# Returns subset of DataFrame for which density is > 100 and columns are population or density

          population     density
New York    19651127  139.076746
Florida     19552860  114.806121

>Any of these indexing conventions may also be used to set or modify values; this is done in the standard way that you might be accustomed to from working with NumPy:

In [21]:
state.iloc[0, 2] = 90
print(state, "\n")

            population    area     density
California    38332521  423967   90.000000
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

Practice indexing via basic indexing, slicing, masking, and fancy indexing using DataFrames:

In [22]:
state # full DataFrame printed for reference to check results below

            population    area     density
California    38332521  423967   90.000000
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [24]:
# Basic indexing with iloc:
print(state.iloc[0,0], "\n")
print(state.iloc[1,1], "\n")
print(state.iloc[2,2], "\n")
print(state.iloc[4,2], "\n")

# Slicing with iloc:
print(state.iloc[2,:], "\n")
print(state.iloc[1:3,0:1], "\n")
print(state.iloc[3:4,[1,2]], "\n")

# Masking with loc (not iloc):
print(state.loc[state.area < 150000, ['area', 'population']])

38332521

695662

139.07674614464568

85.88376279209307

population    1.965113e+07
area          1.412970e+05
density       1.390767e+02
Name: New York, dtype: float64

          population
Texas       26448193
New York    19651127

           area     density
Florida  170312  114.806121

            area  population
New York  141297    19651127
Illinois  149995    12882135

## Additional indexing conventions

> There are a couple extra indexing conventions that might seem at odds with the preceding discussion, but nevertheless can be very useful in practice. 

> First, while indexing refers to columns, slicing refers to rows:

In [28]:
print(state['Florida':'Illinois'], "\n") # We sliced here by explicitly named rows
print(state[3:5], "\n") # We sliced here by implicitly numbered rows

#print(state[3:5, 0:2]) # This line doesn't work, because we can't slice by column without using iloc

print(state.iloc[3:5, 0:2]) # This line does work because we slice by column using iloc instead

          population    area     density
Florida     19552860  170312  114.806121
Illinois    12882135  149995   85.883763

          population    area     density
Florida     19552860  170312  114.806121
Illinois    12882135  149995   85.883763

          population    area
Florida     19552860  170312
Illinois    12882135  149995

> Similarly, direct masking operations are also interpreted row-wise rather than column-wise:

In [29]:
state[state.density > 100] # this returns the ROWS for which this holds, but not the columns for which it holds 
# it only works for a given row index of a DataFrame, not for column names

          population    area     density
New York    19651127  141297  139.076746
Florida     19552860  170312  114.806121

## Index alignment

I'm skipping a bunch of stuff in the text, but want to show this important and useful feature of `Series`.

> For binary operations on two `Series` or `DataFrame` objects, Pandas will align indices in the process of performing the operation. This is very convenient when working with incomplete data, as we'll see in some of the examples that follow.

In [30]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [31]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

Notice how Pandas seamlessly manages the combination of these partially overlapping `Series` indices.

## Operating on Data in Pandas

## Handling Missing Data

> The difference between data found in many tutorials and data in the real world is that real-world data is rarely clean and homogeneous. In particular, many interesting datasets will have some amount of data missing. To make matters even more complicated, different data sources may indicate missing data in different ways.

> There are a number of schemes that have been developed to indicate the presence of missing data in a table or DataFrame. Generally, they revolve around one of two strategies: using a **mask** that globally indicates missing values, or choosing a **sentinel** value that indicates a missing entry.

### `None`: Pythonic missing data

> The first sentinel value used by Pandas is `None`, a Python singleton object that is often used for missing data in Python code. Because it is a Python object, `None` cannot be used in any arbitrary NumPy/Pandas array, but only in arrays with data type `'object'` (i.e., arrays of Python objects):

In [35]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

### `NaN`: Missing numerical data

> The other missing data representation, `NaN` (acronym for Not a Number), is different; it is a special floating-point value recognized by all systems that use the standard IEEE floating-point representation:

In [36]:
vals2 = np.array([1, np.nan, 3, 4])
vals2

array([ 1., nan,  3.,  4.])

But be a bit careful...`NaN` "is a bit like a data virus–it infects any other object it touches."

In [38]:
vals2.sum(), vals2.min(), vals2.max()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [39]:
# There are some NaN aware functions
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(np.float64(8.0), np.float64(1.0), np.float64(4.0))

> Keep in mind that `NaN` is specifically a floating-point value; there is no equivalent `NaN` value for integers, strings, or other types.

## Dealing with null values

In [40]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [41]:
# Detecting null values
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [69]:
# Use a boolean mask to get non-null values
data[data.notnull()]

0        1
2    hello
dtype: object

## Dropping Null Values

The [dropna()] function removes NA values.

In [70]:
# Or more simply dropna
data.dropna()

0        1
2    hello
dtype: object

In [43]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [62]:
# dropna by default drops rows with NaN
df.dropna()

     0    1  2
1  2.0  3.0  5

In [63]:
# Or use axis= 1 or axis='columns' to remove columns with NAs instead of rows
print(df.dropna(axis=1), "\n")

print(df.dropna(axis='columns'), "\n")

   2
0  2
1  5
2  6

   2
0  2
1  5
2  6

In [73]:
# The 'how' and 'thresh' parameters let you decide how many NAs to remove and how many to allow.

# The 'how' parameter has two options ('all' or 'any'), which will remove rows or columns with all missing values or those with any missing values, respectively.
print(df, "\n")
print(df.dropna(axis='columns', how='any'), "\n")
print(df.dropna(axis='columns', how='all'), "\n")

# Thresh gives the minimum number of non-NaN values to keep
df.dropna(thresh=3)

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

   2
0  2
1  5
2  6

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

     0    1  2
1  2.0  3.0  5

In [74]:
# The isnull() function returns a Boolean mask over the data, reporting which values are NaN or None (==TRUE) and which are not (==FALSE)
print(df.isnull(), "\n")
print(data.isnull(), "\n")

# The notnull() function does the same with an inverted Boolean mask, reporting which values are NOT missing (==TRUE) and which are (==FALSE)
print(df.notnull(), "\n")
print(data.notnull(), "\n")

       0      1      2
0  False   True  False
1  False  False  False
2   True  False  False

0    False
1     True
2    False
3     True
dtype: bool

       0      1     2
0   True  False  True
1   True   True  True
2  False   True  True

0     True
1    False
2     True
3    False
dtype: bool

## Filling Null Values

> Sometimes rather than dropping `NA` values, you'd rather replace them with a valid value. This value might be a single number like zero, or it might be some sort of imputation or interpolation from the good values. You could do this in-place using the `isnull()` method as a mask, but because it is such a common operation Pandas provides the `fillna()` method, which returns a copy of the array with the null values replaced.

In [75]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [76]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [77]:
# forward-fill
data.fillna(method='ffill')

/tmp/ipykernel_4182/3316037056.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [79]:
# back-fill
data.fillna(method='bfill')

/tmp/ipykernel_4182/692461307.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [80]:
# Similar in DataFrames

df[3] = np.nan # I skipped a step earlier where the text added a column of NaNs
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [84]:
df.fillna(method='ffill', axis=1)

/tmp/ipykernel_4182/901808322.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=1)

     0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

## Combining DataFrames

> Recall that np.concatenate() is used to concatenate NumPy arrays:

In [4]:
# Recall that np.concatenate() is used to concatenate NumPy arrays:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
print(np.concatenate([x, y, z]), "\n")

# The first argument is a list or tuple of arrays to concatenate. 
# Additionally, it takes an axis keyword that allows you to specify the axis along which the result will be concatenated:
x = [[1, 2],
     [3, 4]]
print(np.concatenate([x, x], axis=1), "\n")

print(np.concatenate([x, x], axis=0), "\n")

[1 2 3 4 5 6 7 8 9]

[[1 2 1 2]
 [3 4 3 4]]

[[1 2]
 [3 4]
 [1 2]
 [3 4]]

> Pandas has a function, pd.concat(), which has a similar syntax to np.concatenate but contains a number of options...

Signature in Pandas v0.18:

pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, 
          verify_integrity=False, copy=True)]

> pd.concat() can be used for a simple concatenation of Series or DataFrame objects, just as np.concatenate() can be used for simple concatenations of arrays:

In [3]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

> It also works to concatenate higher-dimensional objects, such as DataFrames:

In [7]:
# For convenience, we'll define this function which creates a DataFrame of a particular form that will be useful below:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3))

# Now we'll use the function to show the two dataframes separated and concatenated:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1, "\n"); print(df2, "\n"); print(pd.concat([df1, df2]), "\n")

    A   B
1  A1  B1
2  A2  B2

    A   B
3  A3  B3
4  A4  B4

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

> By default, the concatenation takes place row-wise within the DataFrame (i.e., axis=0). Like np.concatenate, pd.concat allows specification of an axis along which concatenation will take place. Consider the following example:

In [10]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
print(df3, "\n"); print(df4, "\n"); print(pd.concat([df3, df4], axis=1), "\n")

    A   B
0  A0  B0
1  A1  B1

    C   D
0  C0  D0
1  C1  D1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

> In the simple examples we just looked at, we were mainly concatenating DataFrames with shared column names. In practice, data from different sources might have different sets of column names, and pd.concat offers several options in this case. Consider the concatenation of the following two DataFrames, which have some (but not all!) columns in common:

In [13]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5, "\n"); print(df6, "\n"); print(pd.concat([df5, df6]), "\n")

# By default, the entries for which no data is available are filled with NA values. 

# To change this, we can specify one of several options for the join and join_axes parameters of the concatenate function. 
# By default, the join is a union of the input columns (join='outer').
# However, we can change this to an intersection of the columns using join='inner':
print(pd.concat([df5, df6], join='inner'), "\n")

    A   B   C
1  A1  B1  C1
2  A2  B2  C2

    B   C   D
3  B3  C3  D3
4  B4  C4  D4

     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

#### Merging data frames with the merge function
> The pd.merge() function implements a number of types of joins: the one-to-one, many-to-one, and many-to-many joins.

In [24]:
# One-to-one joins:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
df3 = pd.merge(df1, df2)
print(df1, "\n", df2, "\n", df3, "\n")

# The pd.merge() function recognizes that each DataFrame has an "employee" column. 
# It automatically joins using this column as a key. 
# The result of the merge is a new DataFrame that combines the information from the two inputs.

# Many-to-one joins: Many-to-one joins are joins in which one of the two key columns contains duplicate entries. 
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
print(df3, "\n", df4, "\n", pd.merge(df3, df4), "\n")


# Many-to-many joins: Described in the textbook.

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
   employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
          group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
   employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve